import { useMemo, useState } from "react";
import { DEFAULT_PET_DESIGN, previewPetDesign } from "../../lib/pet-designer";
import type { PetDesignRequest, PetStyle } from "../../types/pet-designer";

const styles: PetStyle[] = ["auto", "pixel", "plush", "clay", "sticker", "flat-vector", "3d-toy"];

export function PetDesignerLab() {
  const [design, setDesign] = useState<PetDesignRequest>(DEFAULT_PET_DESIGN);
  const [started, setStarted] = useState(false);
  const [copied, setCopied] = useState(false);
  const preview = useMemo(() => previewPetDesign(design), [design]);
  const set = <K extends keyof PetDesignRequest>(key: K, value: PetDesignRequest[K]) => setDesign((current) => ({ ...current, [key]: value }));
  const field = (label: string, key: "name" | "species" | "personality" | "palette" | "prop") => <label className="text-xs text-muted">{label}<input value={design[key]} onChange={(e) => set(key, e.target.value)} className="mt-1 w-full rounded-lg border border-border/60 bg-canvas p-2.5 text-sm text-text" /></label>;
  const copyBrief = async () => {
    await navigator.clipboard?.writeText(preview.prompt);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  };
  return <main className="notebook-lab min-h-screen overflow-y-auto bg-canvas p-6 text-text md:p-10"><div className="mx-auto max-w-6xl">
    <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><div className="text-[11px] uppercase tracking-[0.24em] text-accent2">Experimental surface</div><h1 className="mt-2 text-3xl font-medium">Design your pet</h1><p className="mt-2 max-w-2xl text-sm text-muted">Shape the identity first. Hatching remains a separate, validated v2 asset workflow.</p></div><div className="rounded-lg border border-border/60 bg-surface px-3 py-2 text-right text-[11px] text-muted"><div className="font-mono text-text">?experimental=pet-designer</div><div>renderer-only lab</div></div></div>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-xl border border-border/60 bg-surface p-5"><div className="grid gap-4 sm:grid-cols-2">{field("Name", "name")}{field("Species or form", "species")}<label className="text-xs text-muted sm:col-span-2">Description<textarea value={design.description} onChange={(e) => set("description", e.target.value)} rows={2} className="mt-1 w-full resize-y rounded-lg border border-border/60 bg-canvas p-2.5 text-sm text-text" /></label><label className="text-xs text-muted">Style<select value={design.style} onChange={(e) => set("style", e.target.value as PetStyle)} className="mt-1 w-full rounded-lg border border-border/60 bg-canvas p-2.5 text-sm text-text">{styles.map((style) => <option key={style}>{style}</option>)}</select></label>{field("Signature prop", "prop")}{field("Personality", "personality")}{field("Palette", "palette")}</div><div className="mt-6 rounded-lg border border-accent2/30 bg-accent2/5 p-4"><div className="flex items-center justify-between gap-3"><div className="text-[11px] uppercase tracking-wide text-accent2">Generation brief</div><button type="button" onClick={copyBrief} className="rounded-md border border-accent2/30 px-2 py-1 text-[10px] text-accent2 hover:bg-accent2/10">{copied ? "Copied" : "Copy brief"}</button></div><p className="mt-2 text-xs leading-5 text-muted">{preview.prompt}</p></div><div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" onClick={() => setStarted(true)} className="rounded-lg bg-accent2 px-4 py-2.5 text-xs font-medium text-white hover:opacity-90">{started ? "Hatching plan ready" : "Start hatching"}</button>{started && <span className="text-xs text-green">Your design is ready for the validated sprite pipeline.</span>}</div>{started && <div className="mt-4 rounded-lg border border-green/30 bg-green/5 p-4 text-xs text-muted"><div className="font-medium text-green">Next action</div><p className="mt-1">Run the hatch-pet workflow with this brief. It will generate the canonical look, animation rows, look directions, and QA artifacts before packaging.</p><code className="mt-2 block overflow-x-auto rounded bg-canvas p-2 text-[10px] text-text">prepare_pet_run.py --pet-name {design.name} --style-preset {design.style}</code></div>}</section>
      <aside className="space-y-4"><div className="rounded-xl border border-border/60 bg-surface p-5"><div className="text-[11px] uppercase tracking-wide text-faint">Hatch contract</div><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{[["Sprite version", "v2"], ["Atlas", "8 × 11"], ["Cell size", "192 × 208"], ["Directions", "16"]].map(([label, value]) => <div key={label} className="rounded-lg bg-canvas p-3"><div className="text-muted">{label}</div><div className="mt-1 font-mono text-text">{value}</div></div>)}</div><div className="mt-4 text-xs text-green">Ready for canonical base generation</div></div><div className="rounded-xl border border-border/60 bg-surface p-5"><div className="text-[11px] uppercase tracking-wide text-faint">Next stages</div><ol className="mt-3 space-y-2 text-xs text-muted"><li><span className="text-green">✓</span> Identity brief</li><li className={started ? "text-green" : ""}><span className="text-accent2">{started ? "✓" : "2."}</span> Generate main look</li><li>3. Generate and QA 9 states + look rows</li><li>4. Package validated atlas</li></ol></div></aside></div>
  </div></main>;
}
